export const menuArray = [
  {
    id: 1,
    src: '/MenuImages/MenuPage1.jpg',
    alt: 'Menu Page',
    width: 240,
    height: 240,
    category: 'Title',
  },
  {
    id: 2,
    src: '/MenuImages/MenuPage2.jpg',
    alt: 'Menu Page',
    width: 240,
    height: 240,
    category: 'Getränke',
  },
  {
    id: 3,
    src: '/MenuImages/MenuPage3.jpg',
    alt: 'Menu Page',
    width: 240,
    height: 240,
    category: 'Getränke',
  },
  {
    id: 4,
    src: '/MenuImages/MenuPage4.jpg',
    alt: 'Menu Page',
    width: 240,
    height: 240,
    category: 'Getränke',
  },
  {
    id: 5,
    src: '/MenuImages/MenuPage5.jpg',
    alt: 'Menu Page',
    width: 240,
    height: 240,
    category: 'TagesMenü',
  },
  {
    id: 6,
    src: '/MenuImages/MenuPage6.jpg',
    alt: 'Menu Page',
    width: 240,
    height: 240,
    category: 'DimSum',
  },
  {
    id: 7,
    src: '/MenuImages/MenuPage7.jpg',
    alt: 'Menu Page',
    width: 240,
    height: 240,
    category: 'DimSum',
  },
  {
    id: 8,
    src: '/MenuImages/MenuPage8.jpg',
    alt: 'Menu Page',
    width: 240,
    height: 240,
    category: 'DimSum',
  },
  {
    id: 9,
    src: '/MenuImages/MenuPage9.jpg',
    alt: 'Menu Page',
    width: 240,
    height: 240,
    category: 'DimSum',
  },
  {
    id: 10,
    src: '/MenuImages/MenuPage10.jpg',
    alt: 'Menu Page',
    width: 240,
    height: 240,
    category: 'DimSum',
  },
  {
    id: 11,
    src: '/MenuImages/MenuPage11.jpg',
    alt: 'Menu Page',
    width: 240,
    height: 240,
    category: 'Vorspeisen',
  },
  {
    id: 12,
    src: '/MenuImages/MenuPage12.jpg',
    alt: 'Menu Page',
    width: 240,
    height: 240,
    category: 'Vorspeisen',
  },
  {
    id: 13,
    src: '/MenuImages/MenuPage13.jpg',
    alt: 'Menu Page',
    width: 240,
    height: 240,
    category: 'Suppen',
  },
  {
    id: 14,
    src: '/MenuImages/MenuPage14.jpg',
    alt: 'Menu Page',
    width: 240,
    height: 240,
    category: 'Hauptspeise',
  },
  {
    id: 15,
    src: '/MenuImages/MenuPage15.jpg',
    alt: 'Menu Page',
    width: 240,
    height: 240,
    category: 'Hauptspeise',
  },
  {
    id: 16,
    src: '/MenuImages/MenuPage16.jpg',
    alt: 'Menu Page',
    width: 240,
    height: 240,
    category: 'Hauptspeise',
  },
  {
    id: 17,
    src: '/MenuImages/MenuPage17.jpg',
    alt: 'Menu Page',
    width: 240,
    height: 240,
    category: 'Hauptspeise',
  },
  {
    id: 18,
    src: '/MenuImages/MenuPage18.jpg',
    alt: 'Menu Page',
    width: 240,
    height: 240,
    category: 'Hauptspeise',
  },
  {
    id: 19,
    src: '/MenuImages/MenuPage19.jpg',
    alt: 'Menu Page',
    width: 240,
    height: 240,
    category: 'Hauptspeise',
  },
  {
    id: 20,
    src: '/MenuImages/MenuPage20.jpg',
    alt: 'Menu Page',
    width: 240,
    height: 240,
    category: 'Hauptspeise',
  },
  {
    id: 21,
    src: '/MenuImages/MenuPage21.jpg',
    alt: 'Menu Page',
    width: 240,
    height: 240,
    category: 'Vegetarisch',
  },
  {
    id: 22,
    src: '/MenuImages/MenuPage22.jpg',
    alt: 'Menu Page',
    width: 240,
    height: 240,
    category: 'ReisNudeln',
  },
  {
    id: 23,
    src: '/MenuImages/MenuPage23.jpg',
    alt: 'Menu Page',
    width: 240,
    height: 240,
    category: 'Nachspeise',
  },
];
